name: Prepare Release
on:
  push:
    branches: [ release ]
    paths-ignore:
      - '**.md'

jobs:
  prepareRelase:
    uses: codenamephp/workflows.chef/blob/main/.github/workflows/prepare-release.yml@main
    with:
      ref: ${{github.ref_name}}
    secrets: inherit